# 일단은 더미로 만듦 - 운영 환경에서 사용할 파일

spring:
  datasource:
    url: jdbc:mysql://your-server:3306/bms
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

file:
  upload-dir: /home/ubuntu/uploads/